name: CI

on: 
  push:
    branches: [master]
  pull_request: 
    branches: [master]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v4
    - name: Hugo setup
      # You may pin to the exact commit or the version.
      # uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f
      uses: peaceiris/actions-hugo@v3.0.0
      with:
        # The Hugo version to download (if necessary) and use. Example: 0.58.2
        extended: true
      # Build site
      - name: Build HUGO Site
        run: hugo
      # Commit site to new branch
      - name: Deploy to GH Pages
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          target-branch: gh-pages
          build-dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
